BaseUrl=https://www.policybazaar.com/
policyBazaar.travelLink=https://travel.policybazaar.com/
policyBazaar.carLink=https://ci.policybazaar.com/
policyBazaar.HealthLink=https://health.policybazaar.com/